INSERT INTO authuserprofilesearch (username,attrname,textvalue,datevalue,numvalue,langcode) VALUES ('executive','fullname','Tommy Executive',NULL,NULL,NULL);
INSERT INTO authuserprofilesearch (username,attrname,textvalue,datevalue,numvalue,langcode) VALUES ('executive','email','t.executive@gmail.com',NULL,NULL,NULL);
INSERT INTO authuserprofilesearch (username,attrname,textvalue,datevalue,numvalue,langcode) VALUES ('account','fullname','John Williams',NULL,NULL,NULL);
INSERT INTO authuserprofilesearch (username,attrname,textvalue,datevalue,numvalue,langcode) VALUES ('account','email','john.williams@fortress.com',NULL,NULL,NULL);
INSERT INTO authuserprofilesearch (username,attrname,textvalue,datevalue,numvalue,langcode) VALUES ('legal','fullname','Monica Brown',NULL,NULL,NULL);
INSERT INTO authuserprofilesearch (username,attrname,textvalue,datevalue,numvalue,langcode) VALUES ('legal','email','monica.brown@fortress.com',NULL,NULL,NULL);
INSERT INTO authuserprofilesearch (username,attrname,textvalue,datevalue,numvalue,langcode) VALUES ('knowledge','fullname','Chandler Bing',NULL,NULL,NULL);
INSERT INTO authuserprofilesearch (username,attrname,textvalue,datevalue,numvalue,langcode) VALUES ('knowledge','email','chandler.bing@fortress.com',NULL,NULL,NULL);
INSERT INTO authuserprofilesearch (username,attrname,textvalue,datevalue,numvalue,langcode) VALUES ('manager','fullname','Jack Wlliams',NULL,NULL,NULL);
INSERT INTO authuserprofilesearch (username,attrname,textvalue,datevalue,numvalue,langcode) VALUES ('manager','email','jack.williams@gmail.com',NULL,NULL,NULL);
