INSERT INTO authgroups (groupname,descr) VALUES ('administrators','Administrators');
INSERT INTO authgroups (groupname,descr) VALUES ('free','Free Access');
INSERT INTO authgroups (groupname,descr) VALUES ('bpm_broker','Bpm Broker');
INSERT INTO authgroups (groupname,descr) VALUES ('bpm_admin','Bpm Admin');
INSERT INTO authgroups (groupname,descr) VALUES ('bpm_manager','Bpm Manager');
INSERT INTO authgroups (groupname,descr) VALUES ('bpm_appraiser','Bpm Appraiser');
INSERT INTO authgroups (groupname,descr) VALUES ('customers','Customers');
INSERT INTO authgroups (groupname,descr) VALUES ('account_executive','Account Executive');
INSERT INTO authgroups (groupname,descr) VALUES ('legal_worker','Legal worker');
INSERT INTO authgroups (groupname,descr) VALUES ('knowledge_worker','Knowledge worker');
