INSERT INTO authuserprofilesearch (username,attrname,textvalue,datevalue,numvalue,langcode) VALUES ('legal','fullname','Tommy Legal',NULL,NULL,NULL);
INSERT INTO authuserprofilesearch (username,attrname,textvalue,datevalue,numvalue,langcode) VALUES ('legal','email','t.legal@gmail.com',NULL,NULL,NULL);
INSERT INTO authuserprofilesearch (username,attrname,textvalue,datevalue,numvalue,langcode) VALUES ('knowledge','fullname','Tommy Knowledge',NULL,NULL,NULL);
INSERT INTO authuserprofilesearch (username,attrname,textvalue,datevalue,numvalue,langcode) VALUES ('knowledge','email','knowledge@gmail.com',NULL,NULL,NULL);
INSERT INTO authuserprofilesearch (username,attrname,textvalue,datevalue,numvalue,langcode) VALUES ('account','fullname','Tommy Account ',NULL,NULL,NULL);
INSERT INTO authuserprofilesearch (username,attrname,textvalue,datevalue,numvalue,langcode) VALUES ('account','email','t.account@gmail.com',NULL,NULL,NULL);
INSERT INTO authuserprofilesearch (username,attrname,textvalue,datevalue,numvalue,langcode) VALUES ('executive','fullname','Tommy Executive',NULL,NULL,NULL);
INSERT INTO authuserprofilesearch (username,attrname,textvalue,datevalue,numvalue,langcode) VALUES ('executive','email','t.executive@gmail.com',NULL,NULL,NULL);
INSERT INTO authuserprofilesearch (username,attrname,textvalue,datevalue,numvalue,langcode) VALUES ('Manager','fullname','Tommy Manager',NULL,NULL,NULL);
INSERT INTO authuserprofilesearch (username,attrname,textvalue,datevalue,numvalue,langcode) VALUES ('Manager','email','t.manager@gmail.com',NULL,NULL,NULL);
