INSERT INTO widgetconfig (pagecode,framepos,widgetcode,config) VALUES ('homepage',12,'fsi-footer',NULL);
INSERT INTO widgetconfig (pagecode,framepos,widgetcode,config) VALUES ('homepage',11,'Loans-3-images ',NULL);
INSERT INTO widgetconfig (pagecode,framepos,widgetcode,config) VALUES ('homepage',7,'Login-Customer',NULL);
INSERT INTO widgetconfig (pagecode,framepos,widgetcode,config) VALUES ('homepage',6,'banner-main-left ',NULL);
INSERT INTO widgetconfig (pagecode,framepos,widgetcode,config) VALUES ('homepage',9,'fsi-club-credit-card',NULL);
INSERT INTO widgetconfig (pagecode,framepos,widgetcode,config) VALUES ('homepage',10,' Credit-card-banner-right',NULL);
INSERT INTO widgetconfig (pagecode,framepos,widgetcode,config) VALUES ('homepage',8,'Welcome-content',NULL);
INSERT INTO widgetconfig (pagecode,framepos,widgetcode,config) VALUES ('applicant',5,'entando-widget-login_form_inspinia',NULL);
INSERT INTO widgetconfig (pagecode,framepos,widgetcode,config) VALUES ('applicant',12,'fsi-footer',NULL);
INSERT INTO widgetconfig (pagecode,framepos,widgetcode,config) VALUES ('applicant',11,'Loans-3-images ',NULL);
INSERT INTO widgetconfig (pagecode,framepos,widgetcode,config) VALUES ('applicant',6,'banner-main-internal',NULL);
INSERT INTO widgetconfig (pagecode,framepos,widgetcode,config) VALUES ('applicant',7,'complete-registration-BPM',NULL);
INSERT INTO widgetconfig (pagecode,framepos,widgetcode,config) VALUES ('applicant',8,'How-to-complete-instructions',NULL);
INSERT INTO widgetconfig (pagecode,framepos,widgetcode,config) VALUES ('dashboard_internal',8,'fsi-customer-overview',NULL);
INSERT INTO widgetconfig (pagecode,framepos,widgetcode,config) VALUES ('dashboard_internal',5,'entando-widget-login_form_inspinia',NULL);
INSERT INTO widgetconfig (pagecode,framepos,widgetcode,config) VALUES ('dashboard_internal',12,'fsi-footer',NULL);
INSERT INTO widgetconfig (pagecode,framepos,widgetcode,config) VALUES ('dashboard_internal',10,'fsi-state',NULL);
INSERT INTO widgetconfig (pagecode,framepos,widgetcode,config) VALUES ('dashboard_internal',9,'fsi-customer-rate',NULL);
INSERT INTO widgetconfig (pagecode,framepos,widgetcode,config) VALUES ('dashboard_internal',6,'fsi-progress-bar',NULL);
INSERT INTO widgetconfig (pagecode,framepos,widgetcode,config) VALUES ('dashboard_internal',11,'fsi-pdf-document',NULL);
INSERT INTO widgetconfig (pagecode,framepos,widgetcode,config) VALUES ('customer_internal',5,'entando-widget-login_form_inspinia',NULL);
INSERT INTO widgetconfig (pagecode,framepos,widgetcode,config) VALUES ('customer_internal',12,'fsi-footer',NULL);
INSERT INTO widgetconfig (pagecode,framepos,widgetcode,config) VALUES ('customer_internal',11,'fsi-registration-form-advanced',NULL);
INSERT INTO widgetconfig (pagecode,framepos,widgetcode,config) VALUES ('customer_internal',8,'fsi-account-user',NULL);
INSERT INTO widgetconfig (pagecode,framepos,widgetcode,config) VALUES ('customer_internal',6,'fsi-application-progress',NULL);
INSERT INTO widgetconfig (pagecode,framepos,widgetcode,config) VALUES ('customer_internal',9,'fsi-form-banking-services',NULL);
INSERT INTO widgetconfig (pagecode,framepos,widgetcode,config) VALUES ('customer_internal',10,'fsi-Declaration',NULL);
INSERT INTO widgetconfig (pagecode,framepos,widgetcode,config) VALUES ('customer_internal',7,'fsi-apllication-breadcrumb',NULL);
